version: '3.8'

services:
  api:
    image: jonathanleedev/clipboard-api-java:latest
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DATABASE_URI: ${DATABASE_URI}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
