version: '3.8'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/cert
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/key
    ports:
      - '8843:8443'
    depends_on:
      - postgres
    volumes:
      - ${SERVER_CERT_PATH}:/opt/keycloak/certs/cert
      - ${SERVER_KEY_PATH}:/opt/keycloak/certs/key